codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  patch:
    default:
      enabled: no
  project:
    default:
      threshold: 0.2

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
